# Data sources: traces, metrics, logs
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: :4317



exporters:

  otlp/tempo:
    endpoint: tempo:4317
    tls:
      insecure: true

  otlp/oteltui:
    endpoint: oteltui:4317
    tls:
      insecure: true



service:

  pipelines:
    traces:
      receivers: [otlp]
      exporters: [otlp/tempo, otlp/oteltui]

  telemetry:
    metrics:
      address: 0.0.0.0:8888
      level: detailed
